### ISSUE TITLE
Season year is hardcoded

### ISSUE THREAD

**Issue by tvthatsme** [qmateub/gatsby-source-nba#1]
First off, this is amazing! I wrote something similar to this in a project of mine, but it would be a lot better to just use this project as a gatsby source plugin.

Your todo list looks pretty good, however, I think its worth adding a way to configure the season year as well.

Are you still interested in working on this project, or have you moved on? I think I'd like to help 😄

**Comment by qmateub** [comment]
Hi @tvthatsme ! 

First of all thanks a lot for taking a look at this and sorry for the late notice! 🙏 

> Are you still interested in working on this project, or have you moved on?

It started as a test for me when I was trying to understand how to create gatsby plugins 😅 but as you can see it got a little bit outdated 🤦‍♂ 

I could for sure spend some time on this and upgrade it so can be used in Gatsby v2 and blablabla . Let me see if I can find some time this week for doing it 💪 

Regarding the title of your issue, did you think in a cool way of handling the Season year? Maybe as a param of the plugin when you define it 🤔

**Comment by tvthatsme** [comment]
Hey @qmateub !

Thanks for the response 😄 I raised the issue more to poke and see if the project was alive or if you had moved on. Are you still interested in working on it?

If you'd like to accept some pull requests, I think I might have some ideas (including the season) on how to continue making it really cool. With the NBA season winding down, I might be taking things slower, but I'd definitely like to work at it!

If you've moved on, I might take your project as a starting point and make my own. But if you'd like to work on it together, I'm happy to contribute to your project 😄

**Comment by qmateub** [comment]
Hi again @tvthatsme !

As you can see, I updated a little bit the repo to update dependencies, fix vulnerabilities and some other minor improvements.

> Are you still interested in working on it?

Fore sure I am🎉 and looking forward to read your ideas. Makes sense if we close this issue and try to discuss your ideas in separate issues or how do you want to proceed in order to add new cool stuff to the plugin? 😋
